### PR TITLE
Add a filter based on effect

### PR DESCRIPTION
**Pull request by chodyo**
Hi there! I'm not anywhere near done classifying toys but I wanted to bring this to the table early to get your thoughts.

Ever since the toybox was introduced I've found it to be clunky to use unless you know exactly what you're looking for. This change to your addon would add a filter to the toy box that allows players to filter the toybox based on what the toy does.

This change is something I've always wanted, so if you don't want it in your addon, I plan on maintaining this as a fork for myself.

All feedback is welcome!

### CODE REVIEW

**Comment by exochron** [comment]
Hi chodyo, thank you for your pull. You're actually the first code contributor in any of my projects. :)

This feature has been requested for a loong time (https://www.curseforge.com/wow/addons/toy-box-enhanced/issues/3). I was planning to add it in some time. I just didn't want to manually maintain another huge list of ids. So I was aiming for an automatic aproach (or database generator). But I haven't found any nice source to parse from, yet. Well, and so time went on and I kinda forgot about it. ._.
Anyway, the manual approach works definitely as well. So this pull is definetly going in after some fine tuning.

- You're using "use" as key/name for this filter. I'd rather go with "effect" or something similar. Just to have a bit more meaningful name.
- We can also add another layer to the filter menu. So there's a lot of space for potential categories. I'm thinking about something like "Transportation" with "Movement", "Heathstone" and "Teleport" as subcategories. So you can go wild with as much categories as you want. I can handle the filter menu later. :)
- Somebody has already started with some categories in Issue 3 (link above). Maybe you can find some inspiration there.
- There should exist some noisy or music related toys. Some categories for those might be nice. (Drums, whistles, juke boxes and so on)

**Comment by chodyo** [comment]
Wow, I combed through what seems like every issue except for that one looking for this feature request! I can't believe I missed that haha.

I definitely feel you on not maintaining another list - it's incredibly time consuming and easy to misclassify.

These suggestions are great! Before I get going with more classification I'll study your comment and the feature request to make sure the approach I take considers these suggestions. Nested lists sound like a great improvement since the flat list is getting quite long.

One thing I'd like to ask from you since you're a seasoned addon developer: is there any way we can modify `Database.lua` from in-game? It would make toy classification significantly easier and faster if we could set toy categories directly in game with a few mouse clicks instead of alt+tabbing and moving text around. Plus I think that might be a nice addition to the release with the feature, to allow users to move toys to the effect categories they prefer.

**Comment by exochron** [comment]
There is no secret editor mode for this. ^^

**Comment by exochron** [comment]
Somebody just uploaded his version: https://www.curseforge.com/wow/addons/toy-box-enhanced/issues/22
It looks nearly complete. I would go with that as first version of categorisation. From there we can narrow down some more.

**Comment by chodyo** [comment]
Great! Thank you for letting me know, I wouldn't have noticed. This will help immensely!

**Comment by chodyo** [comment]
Alright, just marked this ready for review. Some notes:

* The code I wrote is only compatible for one nested filter layer. If we want to do more layers I'd need to make some parts recursive, but I was assuming we wouldn't want to create too many layers.
* Using the same name for filters is not supported, so I renamed profession effect categories slightly. This also got me when I created multiple `Other` categories so those got renamed too to be just as inclusive but more specific.
* I forked [a spreadsheet](https://docs.google.com/spreadsheets/d/1jCs-9L21Tdi6gxj4_xyNhxEF3QO5yFI2n3SdWjuOVgc/edit?usp=sharing) from issue 22 on curseforge to keep everything organized. This helped massively - I was able to validate itemIDs programmatically with their names to ensure all itemIDs are correct.
  - I'd like to keep it in sync with the addon as much as possible. Categorizing everything directly in the code like I was doing before was slow and tedious and prone to mistakes. I'd be happy to add you as an editor to it, or you can just fork it yourself if you'd like to keep your own separate copy.
* If you turn off all effect filters, it will show everything that's not categorized by effect. This is very handy for checking if we didn't categorize any toys - I found that I had missed like 30 toys originally.
  - There is still just over 1 page of uncategorized toys. A lot of these are shadowlands toys that don't have much info on Wowhead yet.

I feel like this PR is pretty much complete other than the few uncategorized toys. Still open to suggestions of course.

**Review by exochron — APPROVED** [review]

**Comment by exochron** [comment]
Thank you so much for your work! 👍

**Pull request merged**
